#!/bin/bash
# scripts/bundle-mineradio-bridge.sh
# Bundles the Mineradio Bridge extension JS (router.js + api/*.js + vendor/*.mjs) into a single
# IIFE file for JavaScriptCore consumption inside MineradioBridgeEngine.
#
# Prerequisites: Node.js + npm installed.
# Output: TraeFlow/Resources/MineradioBridge/bridge-bundle.js (checked into git)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
EXT_DIR="$REPO_ROOT/Mineradio-Bridge-1.3.1"
OUT_DIR="$REPO_ROOT/TraeFlow/Resources/MineradioBridge"
OUT_FILE="$OUT_DIR/bridge-bundle.js"

echo "[bundle-mineradio-bridge] Extension dir: $EXT_DIR"
echo "[bundle-mineradio-bridge] Output: $OUT_FILE"

mkdir -p "$OUT_DIR"

cd "$EXT_DIR"

if [ ! -d node_modules ]; then
  echo "[bundle-mineradio-bridge] Installing dependencies (npm install)..."
  npm install
fi

echo "[bundle-mineradio-bridge] Running esbuild..."
npx esbuild bridge-entry.js \
  --bundle \
  --format=iife \
  --target=es2020 \
  --outfile="$OUT_FILE" \
  --banner:js="/* Mineradio Bridge bundle — generated by scripts/bundle-mineradio-bridge.sh. DO NOT EDIT. */"

echo "[bundle-mineradio-bridge] Done. Bundle size: $(wc -c < "$OUT_FILE") bytes"
